### ISSUE TITLE
App crashing while I'm turn off the Bluetooth Button from Notification bar

### ISSUE THREAD

**Issue by Roeisteinberg** [gna-sw/Jabra-Perform-BlueParrott-Sample-Android-App-Package#1]
Hello team,

I run a Samsung XCover6  Pro(SM-G736B), running Android 13, API 33
I'm using the latest library for your project.

Case: While I turn off the Bluetooth from the Notification bar, my app crashes (the crash does not happen all the time).

Hope that the detail helps.

Here are the logs 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
                                                                                                    	at com.blueparrott.blueparrottsdk.BPHeadsetImpl.g(Unknown Source:8)
                                                                                                    	at com.blueparrott.blueparrottsdk.BPHeadsetImpl.l(Unknown Source:0)
                                                                                                    	at com.blueparrott.blueparrottsdk.BPHeadsetImpl$2.run(Unknown Source:97)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by alanslattery** [comment]
Hi there,
  Would it be possible to get any of the log from the SDK in the run up to the crash, in order to narrow down exactly where this is happening?

**Comment by Roeisteinberg** [comment]
Sure, I will try to collect that, since ןt rarely comes back
